### ISSUE TITLE
Specify node v 22.x in buildspec

### ISSUE THREAD

**Issue by JoeEdwardsCode** [JoeEdwardsCode/calmap#12]
Runtime version of node needs to be specified in `buildspec.yml` like so:

```yaml
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22.x
    commands:
      - npm install
  build:
    commands:
      - sls deploy --stage dev --verbose
artifacts:
  files:
    - '**/*'
```

This is blocking the serverless dependency from installing.
